["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/paste-plain"]
    type = "archive"
    url = "https://github.com/alfredapp/paste-as-plain-text-from-hotkey-workflow/releases/download/2022.2/Paste.as.Plain.Text.from.Hotkey.alfredworkflow#Paste.as.Plain.Text.from.Hotkey.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/mouseless-messenger"]
    type = "archive"
    url = "https://github.com/stephancasas/alfred-mouseless-messenger/releases/download/v2.0.3/Mouseless.Messenger.alfredworkflow#Mouseless.Messenger.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/menubar"]
    type = "archive"
    url = "https://github.com/BenziAhamed/Menu-Bar-Search/releases/download/v2.0/Menu.Bar.Search.alfredworkflow#menubar-search.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/shortcuts"]
    type = "archive"
    url = "https://github.com/alfredapp/shortcuts-workflow/releases/download/2023.8/Shortcuts.alfredworkflow#Shortcuts.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/recorder"]
    type = "archive"
    url = "https://github.com/vitorgalvao/start-recording-workflow/releases/download/2023.3/Start.Recording.alfredworkflow#recorder.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/fzf"]
    type = "archive"
    url = "https://github.com/yohasebe/fzf-alfred-workflow/raw/main/fzf-alfred-workfow.alfredworkflow#fzf-workflow.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/vscode"]
    type = "archive"
    url = "https://github.com/Acidham/alfred-vscode-workspace-explorer/releases/download/v1.0.0/VSCode.Workspace.Explorer.alfredworkflow#SCode.Workspace.Explorer.zip"
    extract = true
    exclude = ["info.plist"]

["Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/paste-n"]
    type = "archive"
    url = "https://github.com/packal/repository/raw/master/com.bhishanpdl.pastenclipboards/paste_n_clipboards.alfredworkflow"
    extract = true
    exclude = ["info.plist"]